# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ping_pong.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protos/ping_pong.proto", :syntax => :proto3) do
    add_message "ShowCodeRequest" do
      optional :name, :string, 1
    end
    add_message "ShowCodeResponse" do
      optional :id, :int32, 1
      optional :name, :string, 2
      optional :amount, :int32, 3
    end
    add_message "CreateCodeRequest" do
      optional :name, :string, 1
      optional :amount, :int32, 2
    end
    add_message "CodeResponse" do
      optional :id, :int32, 1
      optional :status, :string, 2
    end
    add_message "NumberCollection" do
      repeated :numbers, :int32, 1
    end
    add_message "NumberResponse" do
      optional :sum, :int32, 1
    end
    add_message "PingRequest" do
      optional :sender_name, :string, 1
    end
    add_message "PongRequest" do
      optional :sender_name, :string, 1
    end
    add_message "PongReply" do
      optional :sender_name, :string, 1
    end
    add_message "PingReply" do
      optional :sender_name, :string, 1
    end
  end
end

ShowCodeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ShowCodeRequest").msgclass
ShowCodeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ShowCodeResponse").msgclass
CreateCodeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateCodeRequest").msgclass
CodeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CodeResponse").msgclass
NumberCollection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NumberCollection").msgclass
NumberResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NumberResponse").msgclass
PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PingRequest").msgclass
PongRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PongRequest").msgclass
PongReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PongReply").msgclass
PingReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PingReply").msgclass
